"""Script to generate authentic NT Cyclone / Severe Weather damage tickets and cache their Laya extractions."""
import pandas as pd
import json
from pathlib import Path

CYCLONE_TICKETS = [
    # Darwin Urban & Suburbs
    {"ticket_id": "CYC-001", "property_id": "NT-DAR-201", "location": "Nightcliff", "distance_km": 9, "days_waiting": 1,
     "text": "Category 2 wind gust peeled three Colorbond roof sheets off front bedroom. Heavy rain leaking directly into bedroom and soaking ceiling batts."},
    {"ticket_id": "CYC-002", "property_id": "NT-CAS-202", "location": "Casuarina", "distance_km": 6, "days_waiting": 1,
     "text": "Fallen African mahogany branch sheared overhead service mains into house. Live electrical wire hanging across driveway fence."},
    {"ticket_id": "CYC-003", "property_id": "NT-PAL-203", "location": "Palmerston", "distance_km": 18, "days_waiting": 1,
     "text": "Internal ceiling plasterboard collapsed into hallway under weight of accumulated stormwater from overflowing roof valley. Power isolated."},
    {"ticket_id": "CYC-004", "property_id": "NT-DAR-204", "location": "Darwin City", "distance_km": 4, "days_waiting": 2,
     "text": "Stormwater surcharge backing up through ground-floor laundry and bathroom floor drains. 50mm standing water across living room."},
    {"ticket_id": "CYC-005", "property_id": "NT-BER-205", "location": "Berrimah", "distance_km": 14, "days_waiting": 1,
     "text": "Solar hot water tank frame on roof twisted and displaced by wind. High-pressure copper supply pipe sheared, water gushing onto roof."},
    {"ticket_id": "CYC-006", "property_id": "NT-CAS-206", "location": "Casuarina", "distance_km": 7, "days_waiting": 2,
     "text": "Louvre window frames blown inwards in kitchen during storm squall. Broken glass inside, water driven across electrical appliances."},
    {"ticket_id": "CYC-007", "property_id": "NT-PAL-207", "location": "Palmerston", "distance_km": 19, "days_waiting": 1,
     "text": "External meter box door torn off and water driving directly into main fuses. Tenant reports loud crackling and arcing sparks."},
    {"ticket_id": "CYC-008", "property_id": "NT-DAR-208", "location": "Nightcliff", "distance_km": 10, "days_waiting": 2,
     "text": "Rear verandah corrugated iron awning ripped away from fascia beam. Raw metal edges flapping violently against gas bottle line."},
    {"ticket_id": "CYC-009", "property_id": "NT-PAL-209", "location": "Palmerston", "distance_km": 20, "days_waiting": 1,
     "text": "Major stormwater ingress around front entry door frame. Carpet and structural timber skirting waterlogged and lifting."},
    {"ticket_id": "CYC-010", "property_id": "NT-CAS-210", "location": "Casuarina", "distance_km": 6, "days_waiting": 2,
     "text": "Downpipe severed by fallen tree limb. Concentrated roof discharge pooling against concrete footings and entering subfloor."},
    {"ticket_id": "CYC-011", "property_id": "NT-DAR-211", "location": "Darwin City", "distance_km": 5, "days_waiting": 2,
     "text": "Water pouring from light fixture in central lounge room after roof flashing failure. Light switch causing tingling sensation."},
    {"ticket_id": "CYC-012", "property_id": "NT-PAL-212", "location": "Palmerston", "distance_km": 18, "days_waiting": 3,
     "text": "Storm wind forced rain under eaves into wall cavity. Mould blooming and plasterboard softened around power points."},
    {"ticket_id": "CYC-013", "property_id": "NT-BAT-213", "location": "Batchelor", "distance_km": 98, "days_waiting": 1,
     "text": "Tree fallen across perimeter security fence and crushing external wastewater inspection riser pipe. Sewage leaking into yard."},
    {"ticket_id": "CYC-014", "property_id": "NT-ADL-214", "location": "Adelaide River", "distance_km": 112, "days_waiting": 2,
     "text": "Flash flooding penetrated under back sliding door. 75mm silt and water across rear two bedrooms. Need emergency water extraction."},
    {"ticket_id": "CYC-015", "property_id": "NT-PIN-215", "location": "Pine Creek", "distance_km": 225, "days_waiting": 2,
     "text": "Roof ridge capping dislodged along entire length of house. Active waterfall leaking into roof space and bedroom ceilings."},
    {"ticket_id": "CYC-016", "property_id": "NT-KAT-216", "location": "Katherine", "distance_km": 315, "days_waiting": 1,
     "text": "Katherine River catchment storm runoff overwhelmed back stormwater gully. Water rising towards power outlets on lower floor."},
    {"ticket_id": "CYC-017", "property_id": "NT-KAT-217", "location": "Katherine", "distance_km": 318, "days_waiting": 2,
     "text": "Large gum tree branch smashed through front carport roof, pinning vehicle and bending structural steel stanchion."},
    {"ticket_id": "CYC-018", "property_id": "NT-JAB-218", "location": "Jabiru", "distance_km": 255, "days_waiting": 2,
     "text": "Severe tropical downpour penetrated split system AC wall penetrations. Water running down inside electrical wiring channel."},
    {"ticket_id": "CYC-019", "property_id": "NT-WAD-219", "location": "Wadeye", "distance_km": 420, "days_waiting": 1,
     "text": "Coastal storm surge wind gust lifted rear roof section. Rain entering kitchen, stove and circuit breaker submerged."},
    {"ticket_id": "CYC-020", "property_id": "NT-DAR-220", "location": "Darwin City", "distance_km": 4, "days_waiting": 1,
     "text": "Roof gutter collapsed under extreme tropical rain weight, pulling down timber fascia and exposing electrical conduits."},
    {"ticket_id": "CYC-021", "property_id": "NT-CAS-221", "location": "Casuarina", "distance_km": 7, "days_waiting": 2,
     "text": "Water ingress through roof has caused large bubble in ceiling paint directly over child bedroom bunk bed. Sagging severely."},
    {"ticket_id": "CYC-022", "property_id": "NT-PAL-222", "location": "Palmerston", "distance_km": 19, "days_waiting": 2,
     "text": "Front security door frame warped and jammed shut by storm wind pressure. Main exit completely blocked, tenant cannot exit."},
    {"ticket_id": "CYC-023", "property_id": "NT-DAR-223", "location": "Nightcliff", "distance_km": 10, "days_waiting": 1,
     "text": "High winds snapped external bathroom ventilation cowl. Rain pouring straight down through exhaust fan into shower recess."},
    {"ticket_id": "CYC-024", "property_id": "NT-BER-224", "location": "Berrimah", "distance_km": 14, "days_waiting": 2,
     "text": "Underground drain pipe collapsed during saturation event. Sump overflowing into adjacent house storage room."},
    {"ticket_id": "CYC-025", "property_id": "NT-CAS-225", "location": "Casuarina", "distance_km": 6, "days_waiting": 3,
     "text": "Rear verandah post rotted footings dislodged during storm. Roof corner sagging 150mm, risk of immediate collapse."},
    {"ticket_id": "CYC-026", "property_id": "NT-DAR-226", "location": "Darwin City", "distance_km": 3, "days_waiting": 1,
     "text": "Electrical sub-board humming loudly and smoking after water dripped onto main breaker from ceiling screw penetration."},
    {"ticket_id": "CYC-027", "property_id": "NT-PAL-227", "location": "Palmerston", "distance_km": 17, "days_waiting": 2,
     "text": "Driveway culvert blocked with storm debris. Sheet flow water entering under front sliding doors into living room."},
    {"ticket_id": "CYC-028", "property_id": "NT-BAT-228", "location": "Batchelor", "distance_km": 98, "days_waiting": 2,
     "text": "Kitchen ceiling plaster sheet dropped 100mm with active water dripping onto food prep benchtop."},
    {"ticket_id": "CYC-029", "property_id": "NT-KAT-229", "location": "Katherine", "distance_km": 320, "days_waiting": 1,
     "text": "Water supply line to external laundry ripped from wall by fallen timber fence. Mains water shut off at street."},
    {"ticket_id": "CYC-030", "property_id": "NT-DAR-230", "location": "Nightcliff", "distance_km": 9, "days_waiting": 1,
     "text": "Flying tree branch shattered living room window. Wind driving torrential rain across internal floor and electronics."},
    {"ticket_id": "CYC-031", "property_id": "NT-CAS-231", "location": "Casuarina", "distance_km": 8, "days_waiting": 2,
     "text": "Roof valley gutter clogged with cyclone debris, backing water up under tiles and into roof insulation."},
    {"ticket_id": "CYC-032", "property_id": "NT-PAL-232", "location": "Palmerston", "distance_km": 18, "days_waiting": 2,
     "text": "External safety isolation switch filled with rainwater. Circuit breaker trips immediately when engaged."},
    {"ticket_id": "CYC-033", "property_id": "NT-ADL-233", "location": "Adelaide River", "distance_km": 112, "days_waiting": 3,
     "text": "Septic tank inspection lid dislodged by overland flood waters. Mud and surface runoff draining into septic chamber."},
    {"ticket_id": "CYC-034", "property_id": "NT-PIN-234", "location": "Pine Creek", "distance_km": 225, "days_waiting": 1,
     "text": "Verandah roof corrugated iron sheet peeling up at edge, screeching and banging against chimney in wind."},
    {"ticket_id": "CYC-035", "property_id": "NT-JAB-235", "location": "Jabiru", "distance_km": 255, "days_waiting": 3,
     "text": "Heavy rain penetration through ceiling above switchboard. Power completely dead throughout property."},
    {"ticket_id": "CYC-036", "property_id": "NT-DAR-236", "location": "Darwin City", "distance_km": 4, "days_waiting": 1,
     "text": "Storm wind blew laundry door off hinges. Door frame split, water blowing into interior hallway."},
    {"ticket_id": "CYC-037", "property_id": "NT-PAL-237", "location": "Palmerston", "distance_km": 19, "days_waiting": 2,
     "text": "Hot water heater storage cylinder knocked off concrete pad by fallen tree. Pipe connection snapped and leaking."},
    {"ticket_id": "CYC-038", "property_id": "NT-CAS-238", "location": "Casuarina", "distance_km": 6, "days_waiting": 1,
     "text": "Living room ceiling bowing downwards with heavy pool of water above. Tenant has evacuated room fearing collapse."},
    {"ticket_id": "CYC-039", "property_id": "NT-DAR-239", "location": "Nightcliff", "distance_km": 10, "days_waiting": 2,
     "text": "Stormwater grates blocked by palm fronds. Yard completely submerged and water lapping at floor level threshold."},
    {"ticket_id": "CYC-040", "property_id": "NT-KAT-240", "location": "Katherine", "distance_km": 315, "days_waiting": 2,
     "text": "Bedroom louvres shattered by flying roof tile from neighbouring property. Torrential rain soaking mattress and floor."},
    {"ticket_id": "CYC-041", "property_id": "NT-BER-241", "location": "Berrimah", "distance_km": 14, "days_waiting": 1,
     "text": "Stormwater ponding against foundation wall. Water seeping through masonry into dining room skirting."},
    {"ticket_id": "CYC-042", "property_id": "NT-DAR-242", "location": "Darwin City", "distance_km": 5, "days_waiting": 3,
     "text": "Exhaust ducting on roof displaced. Rain entering kitchen rangehood and dripping onto gas cooktop."},
    {"ticket_id": "CYC-043", "property_id": "NT-PAL-243", "location": "Palmerston", "distance_km": 20, "days_waiting": 1,
     "text": "Ceiling fan in bedroom sparking after water penetrated roof cavity and dripped through motor housing."},
    {"ticket_id": "CYC-044", "property_id": "NT-CAS-244", "location": "Casuarina", "distance_km": 7, "days_waiting": 2,
     "text": "Cyclone wind sheared TV antenna from roof, puncturing two holes through iron roof sheets above master bedroom."},
    {"ticket_id": "CYC-045", "property_id": "NT-BAT-245", "location": "Batchelor", "distance_km": 98, "days_waiting": 1,
     "text": "Rainwater gutter overflowed behind eaves board, causing extensive water saturation of ceiling insulation."},
    {"ticket_id": "CYC-046", "property_id": "NT-ADL-246", "location": "Adelaide River", "distance_km": 112, "days_waiting": 2,
     "text": "Corrugated roof sheets loose on outbuilding storage shed. Sheets lifting 300mm in gusts, hazard to tenants."},
    {"ticket_id": "CYC-047", "property_id": "NT-DAR-247", "location": "Nightcliff", "distance_km": 9, "days_waiting": 1,
     "text": "Main water meter assembly damaged by uprooted tree. High-pressure town water spraying across footpath."},
    {"ticket_id": "CYC-048", "property_id": "NT-PAL-248", "location": "Palmerston", "distance_km": 18, "days_waiting": 3,
     "text": "Water dripping steadily from screw holes in hallway smoke alarm. Smoke alarm sounding continuously."},
    {"ticket_id": "CYC-049", "property_id": "NT-KAT-249", "location": "Katherine", "distance_km": 315, "days_waiting": 2,
     "text": "Severe wind damaged roof ventilator (whirlybird), leaving open 350mm hole with torrential water pouring inside."},
    {"ticket_id": "CYC-050", "property_id": "NT-PIN-250", "location": "Pine Creek", "distance_km": 225, "days_waiting": 1,
     "text": "Downpipe dislodged at top elbow. Concentrated roof cascade eroding foundation soil under rear bedroom corner."},
]

DATA_DIR = Path(__file__).parent / "data"
DATA_DIR.mkdir(exist_ok=True)
out_path = DATA_DIR / "cyclone_incident_catalog.csv"

df = pd.DataFrame(CYCLONE_TICKETS)
df.to_csv(out_path, index=False)
print(f"Created {out_path} with {len(df)} authentic NT storm damage tickets.")
